backend:
  name: github
  repo: prolocoalbano/proloco-albano
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pagine"
    label: "Pagine"
    files:
      - file: "contenuti.json"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Titolo Principale", name: "titolo", widget: "string"}
          - {label: "Descrizione", name: "descrizione", widget: "text"}
